version: "3"
services:
  nats:
    image: nats:latest
    hostname: nats-server
    command: "-c /tls.conf -DV"
    volumes:
      - "./tls.conf:/tls.conf"
      - "./certs/server.pem:/certs/server.pem"
      - "./certs/server-key.pem:/certs/server-key.pem"
    ports:
      - "4222:4222"
      - "8222:8222"
